keys:
  - &prometheus age18zdvkrse266y9mhlvh86vldp6aq39tr8qu4k2mqc727ngramnu3qynzucy
  - &morpheus age1av6wzrkwm9kg2ym0fr3vyh8ag788c0kuz7w5fwmavw4muelwjvmqmpfnqp
  - &thanatos age1qfy94pqqtvyl47jqe66rzsnahsa6tyme3wh54f0zd56p6wrrf96qjrx9mp
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *prometheus
        - *morpheus
        - *thanatos
